[package]
name = "edgecoin"
version = "0.1.0"
edition = "2021"

[dependencies]
rsa = "0.9.6"
serde_json = "1.0.122"
serde = { version = "1.0.204", features = ["derive"] }
clap = { version = "4.4.8", features = ["derive"] }
rustyline = "14.0.0"
ratatui = "0.27.0"
crossterm = "0.28.1"
